stages:
  - test

before_script:
  - apk add bash curl
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH

.job_template: &job_definition
  stage: test
  cache:
    key: '$CI_BUILD_NAME-$CI_COMMIT_REF_SLUG'
    paths:
      - node_modules/
  script:
    - yarn --non-interactive
    - yarn lint
    - yarn test

Node 8:
  <<: *job_definition
  image: node:8-alpine

Node 10:
  <<: *job_definition
  image: node:10-alpine
